services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: Пользователи}
        arguments:
            - ~
            - AppBundle\Entity\Users
            - AppBundle:User
        calls:
            - [ setTemplate, [show, SonataAdminBundle:CRUD:user_base_show.html.twig]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore'] ]

    app.admin.course:
        class: AppBundle\Admin\CourseAdmin
        arguments:
            - ~
            - AppBundle\Entity\Course
            - AppBundle:Course
        tags:
            - { name: sonata.admin, manager_type: orm, label: Список курсов }
        calls:
            - [setTemplate, [show, SonataAdminBundle:CRUD:course_base_show.html.twig]]
            - [setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]

    app.admin.group:
        class: AppBundle\Admin\GroupAdmin
        arguments:
            - ~
            - AppBundle\Entity\Groups
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: Группы }
        calls:
            - [setTemplate, [show, SonataAdminBundle:CRUD:groups_base_show.html.twig]]
            - [setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]

#    app.admin.lessons:
#        class: AppBundle\Admin\LessonsAdmin
#        arguments: [~, AppBundle\Entity\Lessons, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Занятия }
#
#    app.admin.home_assignment:
#        class: AppBundle\Admin\HomeAssignmentAdmin
#        arguments: [~, AppBundle\Entity\HomeAssignment, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Домашнее задание }

    sonata.block.profile.layout:
        class: AppBundle\Block\ProfileLayoutBlock
        arguments:
            - sonata.block.profile.layout
            - "@templating"
        tags:
            - { name: sonata.block }

    twig.extension.user.handle:
        class: AppBundle\Twig\Handle\UserHandle
        arguments:
            - "@service_container"

    app.soft_delete_listener:
        class: AppBundle\Events\SoftDeleteListener
        tags:
            - { name: doctrine.event_listener, event: preSoftDelete, priority: 10 }

    app.explode_lessons:
        class: AppBundle\Service\ExplodeLessons

    app.home:
        class: AppBundle\Controller\HomeController
        autowire: true
        public: true